#!/usr/bin/env python3
import requests
import sys

# config poet
default_poet = '2'

if len(sys.argv) > 1 and sys.argv[1]:
    poet = str(sys.argv[1])
else:
    poet = default_poet

try:
    poem = requests.get(
        'http://c.ganjoor.net/beyt-json.php?p=' + poet,
        timeout=2
    ).json()
    print(
        '\n\n\t' + poem['m1'] + '\n\t' + poem['m2'] +
        '\n\t\t' + poem['poet'] + '\n')
except Exception as e:
    print('دسترسی به اینترنت وجود ندارد')
