#!/usr/bin/env python3
import requests

poet = '2'
try:
    poem = requests.get('http://c.ganjoor.net/beyt-json.php?p=' + poet).json()
    print(
        '\n\n\t' + poem['m1'] + '\n\t' + poem['m2'] +
        '\n\t\t' + poem['poet'] + '\n')
except Exception as e:
    print('دسترسی به اینترنت وجود ندارد')
